version: '3'

services:

  #####################
  ### WebApp Nodejs
  #####################
  nodeapp:
    restart: unless-stopped
    build: ./
    networks:
      - node_network

  #####################
  ### Nginx Proxy
  #####################
  proxy:
    restart: unless-stopped
    image: nginx:stable
    ports:
      - "8010:80"
    depends_on:
      - nodeapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network: